-- Create partners table
CREATE TABLE public.partners (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  name_en TEXT NOT NULL DEFAULT '',
  name_ar TEXT NOT NULL DEFAULT '',
  logo_url TEXT,
  website_url TEXT,
  sort_order INTEGER NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

ALTER TABLE public.partners ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Anyone can read partners"
ON public.partners
FOR SELECT
TO anon, authenticated
USING (true);

-- Section content keys (tag, title, subtitle) - English only; Arabic auto-generated by translate function
INSERT INTO public.site_content (content_key, value_en, value_ar) VALUES
  ('partners.tag', 'Our Partners', 'شركاؤنا'),
  ('partners.title', 'Trusted by Industry Leaders', 'موثوق به من قبل قادة الصناعة'),
  ('partners.subtitle', 'We collaborate with world-class brands to deliver excellence.', 'نتعاون مع علامات تجارية عالمية المستوى لتحقيق التميز.')
ON CONFLICT (content_key) DO NOTHING;

-- Seed dummy partners
INSERT INTO public.partners (name_en, name_ar, sort_order) VALUES
  ('Siemens', 'سيمنز', 1),
  ('ABB', 'إيه بي بي', 2),
  ('Schneider Electric', 'شنايدر إلكتريك', 3),
  ('Honeywell', 'هانيويل', 4),
  ('Emerson', 'إيمرسون', 5),
  ('Rockwell Automation', 'روكويل أوتوميشن', 6),
  ('Bosch', 'بوش', 7),
  ('Mitsubishi Electric', 'ميتسوبيشي إلكتريك', 8);