// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xemoqcukwjcmnzqcdrey.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhlbW9xY3Vrd2pjbW56cWNkcmV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM1NjkzMzgsImV4cCI6MjA4OTE0NTMzOH0.YaYxY1OHBXHR3hUzxeLuwHca68IPM7v0MH3U3tkB0dA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});